test:
	@cargo test --quiet -- --nocapture

lsp:
	@RUST_BACKTRACE=1 cargo test --quiet parse_l1lsp_test_1 -- --nocapture

hello:
	@cargo test --quiet parse_l1hello_test -- --nocapture

csnp:
	@cargo test --quiet parse_csnp -- --nocapture

psnp:
	@cargo test --quiet parse_psnp -- --nocapture

l2:
	@cargo test --quiet parse_l2 -- --nocapture

json:
	@cargo test --quiet json_test -- --nocapture

sid:
	@cargo test --quiet sid -- --nocapture

srv6:
	@cargo test --quiet srv6 -- --nocapture

p2p:
	@cargo test --quiet parse_p2p_hello -- --nocapture
