name: Build for arm64

on: [ workflow_dispatch ]

jobs:
  build:
    name: Build for arm64
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build cli
        run: |
          sudo apt update -y
          sudo atp upgrade -y
          sudo apt install -y protobuf-compiler
          cd cli
          ./configure
          make
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm
          cd ../packaging
          make arm64

      - name: Upload basefs artifact
        uses: actions/upload-artifact@v4
        with:
          name: zebra-rs-arm64
          path: |
            ./packaging/*.deb
